[2025-11-01T16:31:36.419+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:31:33.432905+00:00 [queued]>
[2025-11-01T16:31:36.439+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:31:33.432905+00:00 [queued]>
[2025-11-01T16:31:36.440+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T16:31:36.472+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_csv_to_clickhouse> on 2025-11-01 16:31:33.432905+00:00
[2025-11-01T16:31:36.498+0000] {standard_task_runner.py:60} INFO - Started process 220 to run task
[2025-11-01T16:31:36.508+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_clickhouse', 'load_csv_to_clickhouse', 'manual__2025-11-01T16:31:33.432905+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/load_to_clickhouse.py', '--cfg-path', '/tmp/tmp2uol3_fh']
[2025-11-01T16:31:36.513+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask load_csv_to_clickhouse
[2025-11-01T16:31:36.685+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:31:33.432905+00:00 [running]> on host 4944221c0f0f
[2025-11-01T16:31:38.727+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_csv_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T16:31:33.432905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T16:31:33.432905+00:00'
[2025-11-01T16:31:38.732+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_clickhouse.py", line 13, in load_csv_to_clickhouse
    raise FileNotFoundError(f"CSV fail puudub: {file_path}")
FileNotFoundError: CSV fail puudub: /opt/***/data/MTR_2025-11-01.csv
[2025-11-01T16:31:38.781+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_csv_to_clickhouse, task_id=load_csv_to_clickhouse, execution_date=20251101T163133, start_date=20251101T163136, end_date=20251101T163138
[2025-11-01T16:31:38.821+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 6 for task load_csv_to_clickhouse (CSV fail puudub: /opt/***/data/MTR_2025-11-01.csv; 220)
[2025-11-01T16:31:38.904+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T16:31:38.957+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
