[2025-11-01T16:53:00.006+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:52:54.094279+00:00 [queued]>
[2025-11-01T16:53:00.053+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:52:54.094279+00:00 [queued]>
[2025-11-01T16:53:00.054+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T16:53:00.112+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_csv_to_clickhouse> on 2025-11-01 16:52:54.094279+00:00
[2025-11-01T16:53:00.139+0000] {standard_task_runner.py:60} INFO - Started process 197 to run task
[2025-11-01T16:53:00.151+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_clickhouse', 'load_csv_to_clickhouse', 'manual__2025-11-01T16:52:54.094279+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/load_to_clickhouse.py', '--cfg-path', '/tmp/tmp80ryaj_9']
[2025-11-01T16:53:00.176+0000] {standard_task_runner.py:88} INFO - Job 13: Subtask load_csv_to_clickhouse
[2025-11-01T16:53:00.626+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:52:54.094279+00:00 [running]> on host 4944221c0f0f
[2025-11-01T16:53:04.934+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_csv_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T16:52:54.094279+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T16:52:54.094279+00:00'
[2025-11-01T16:53:05.489+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_clickhouse.py", line 25, in load_csv_to_clickhouse
    client.execute(f"""
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 382, in execute
    rv = self.process_ordinary_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 580, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 212, in receive_result
    return result.get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 228, in packet_generator
    packet = self.receive_packet()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 245, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 60.
DB::Exception: Could not find table: bronze_mtr_raw. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
3. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000cb04dab
4. DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x00000000182ce3bf
5. DB::InterpreterAlterQuery::execute() @ 0x00000000182c938d
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018780440
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
8. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
9. DB::TCPHandler::run() @ 0x0000000019e4f119
10. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
11. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
12. Poco::PooledThread::run() @ 0x000000001ef15b87
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
14. ? @ 0x0000000000094ac3
15. ? @ 0x0000000000125a74

[2025-11-01T16:53:05.526+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_csv_to_clickhouse, task_id=load_csv_to_clickhouse, execution_date=20251101T165254, start_date=20251101T165300, end_date=20251101T165305
[2025-11-01T16:53:05.560+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 13 for task load_csv_to_clickhouse (Code: 60.
DB::Exception: Could not find table: bronze_mtr_raw. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
3. DB::Exception::Exception<String&>(int, FormatStringHelperImpl<std::type_identity<String&>::type>, String&) @ 0x000000000cb04dab
4. DB::InterpreterAlterQuery::executeToTable(DB::ASTAlterQuery const&) @ 0x00000000182ce3bf
5. DB::InterpreterAlterQuery::execute() @ 0x00000000182c938d
6. DB::executeQueryImpl(char const*, char const*, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum, std::unique_ptr<DB::ReadBuffer, std::default_delete<DB::ReadBuffer>>&, std::shared_ptr<DB::IAST>&, std::shared_ptr<DB::ImplicitTransactionControlExecutor>) @ 0x0000000018780440
7. DB::executeQuery(String const&, std::shared_ptr<DB::Context>, DB::QueryFlags, DB::QueryProcessingStage::Enum) @ 0x00000000187786cb
8. DB::TCPHandler::runImpl() @ 0x0000000019e2d3db
9. DB::TCPHandler::run() @ 0x0000000019e4f119
10. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
11. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
12. Poco::PooledThread::run() @ 0x000000001ef15b87
13. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
14. ? @ 0x0000000000094ac3
15. ? @ 0x0000000000125a74
; 197)
[2025-11-01T16:53:05.633+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T16:53:05.679+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
