[2025-11-01T16:39:46.109+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:39:42.953149+00:00 [queued]>
[2025-11-01T16:39:46.135+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:39:42.953149+00:00 [queued]>
[2025-11-01T16:39:46.137+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T16:39:46.171+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_csv_to_clickhouse> on 2025-11-01 16:39:42.953149+00:00
[2025-11-01T16:39:46.193+0000] {standard_task_runner.py:60} INFO - Started process 197 to run task
[2025-11-01T16:39:46.206+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'load_csv_to_clickhouse', 'load_csv_to_clickhouse', 'manual__2025-11-01T16:39:42.953149+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/load_to_clickhouse.py', '--cfg-path', '/tmp/tmp_heh8vcd']
[2025-11-01T16:39:46.214+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask load_csv_to_clickhouse
[2025-11-01T16:39:46.442+0000] {task_command.py:423} INFO - Running <TaskInstance: load_csv_to_clickhouse.load_csv_to_clickhouse manual__2025-11-01T16:39:42.953149+00:00 [running]> on host 4944221c0f0f
[2025-11-01T16:39:47.035+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_csv_to_clickhouse' AIRFLOW_CTX_TASK_ID='load_csv_to_clickhouse' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T16:39:42.953149+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T16:39:42.953149+00:00'
[2025-11-01T16:39:47.466+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/load_to_clickhouse.py", line 23, in load_csv_to_clickhouse
    client.execute(f"""
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 370, in execute
    with self.disconnect_on_error(query, settings):
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 313, in disconnect_on_error
    self.establish_connection(settings)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 300, in establish_connection
    self.connection.force_connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 258, in force_connect
    self.connect()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 399, in connect
    return self._init_connection(host, port)
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 343, in _init_connection
    self.receive_hello()
  File "/home/airflow/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 528, in receive_hello
    raise self.receive_exception()
clickhouse_driver.errors.ServerException: Code: 516.
DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
3. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ClientInfo const&) const @ 0x0000000016c5c123
4. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000184732f2
5. DB::Session::authenticate(String const&, String const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000184727b2
6. DB::TCPHandler::receiveHello() @ 0x0000000019e38ff9
7. DB::TCPHandler::runImpl() @ 0x0000000019e29a13
8. DB::TCPHandler::run() @ 0x0000000019e4f119
9. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
10. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
11. Poco::PooledThread::run() @ 0x000000001ef15b87
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
13. ? @ 0x0000000000094ac3
14. ? @ 0x0000000000125a74

[2025-11-01T16:39:47.515+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=load_csv_to_clickhouse, task_id=load_csv_to_clickhouse, execution_date=20251101T163942, start_date=20251101T163946, end_date=20251101T163947
[2025-11-01T16:39:47.548+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task load_csv_to_clickhouse (Code: 516.
DB::Exception: default: Authentication failed: password is incorrect, or there is no user with such name.

If you use ClickHouse Cloud, the password can be reset at https://clickhouse.cloud/
on the settings page for the corresponding service.

If you have installed ClickHouse and forgot password you can reset it in the configuration file.
The password for default user is typically located at /etc/clickhouse-server/users.d/default-password.xml
and deleting this file will reset the password.
See also /etc/clickhouse-server/users.xml on the server where ClickHouse is installed.

. Stack trace:

0. DB::Exception::Exception(DB::Exception::MessageMasked&&, int, bool) @ 0x00000000137a855f
1. DB::Exception::Exception(String&&, int, String, bool) @ 0x000000000cae7e8e
2. DB::Exception::Exception(PreformattedMessage&&, int) @ 0x000000000cae7940
3. DB::AccessControl::authenticate(DB::Credentials const&, Poco::Net::IPAddress const&, DB::ClientInfo const&) const @ 0x0000000016c5c123
4. DB::Session::authenticate(DB::Credentials const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000184732f2
5. DB::Session::authenticate(String const&, String const&, Poco::Net::SocketAddress const&, std::vector<String, std::allocator<String>> const&) @ 0x00000000184727b2
6. DB::TCPHandler::receiveHello() @ 0x0000000019e38ff9
7. DB::TCPHandler::runImpl() @ 0x0000000019e29a13
8. DB::TCPHandler::run() @ 0x0000000019e4f119
9. Poco::Net::TCPServerConnection::start() @ 0x000000001ef4ed07
10. Poco::Net::TCPServerDispatcher::run() @ 0x000000001ef4f199
11. Poco::PooledThread::run() @ 0x000000001ef15b87
12. Poco::ThreadImpl::runnableEntry(void*) @ 0x000000001ef13f81
13. ? @ 0x0000000000094ac3
14. ? @ 0x0000000000125a74
; 197)
[2025-11-01T16:39:47.628+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T16:39:47.704+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
