[2025-11-01T17:26:20.441+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: validate_csv.validate_csv manual__2025-11-01T17:26:12.708987+00:00 [queued]>
[2025-11-01T17:26:20.500+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: validate_csv.validate_csv manual__2025-11-01T17:26:12.708987+00:00 [queued]>
[2025-11-01T17:26:20.502+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2025-11-01T17:26:20.608+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): validate_csv> on 2025-11-01 17:26:12.708987+00:00
[2025-11-01T17:26:20.672+0000] {standard_task_runner.py:60} INFO - Started process 243 to run task
[2025-11-01T17:26:20.761+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'validate_csv', 'validate_csv', 'manual__2025-11-01T17:26:12.708987+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/validate.py', '--cfg-path', '/tmp/tmpn2uffbn9']
[2025-11-01T17:26:20.814+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask validate_csv
[2025-11-01T17:26:22.546+0000] {task_command.py:423} INFO - Running <TaskInstance: validate_csv.validate_csv manual__2025-11-01T17:26:12.708987+00:00 [running]> on host 4944221c0f0f
[2025-11-01T17:26:23.678+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='validate_csv' AIRFLOW_CTX_TASK_ID='validate_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-11-01T17:26:12.708987+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-11-01T17:26:12.708987+00:00'
[2025-11-01T17:26:47.613+0000] {logging_mixin.py:188} INFO - 496
[2025-11-01T17:26:47.664+0000] {logging_mixin.py:188} INFO -                                              Number  ... Arhiveerimise aeg,,,,
1   Tagatise kehtivuse alguskuupäev: 2025-10-28,,,,  ...                  None
4   Tagatise kehtivuse alguskuupäev: 2025-10-17,,,,  ...                  None
26            Tagatise kehtivuse alguskuupäev: ,,,,  ...                  None
29  Tagatise kehtivuse alguskuupäev: 2025-10-07,,,,  ...                  None
67  Tagatise kehtivuse alguskuupäev: 2025-09-29,,,,  ...                  None

[5 rows x 9 columns]
[2025-11-01T17:26:47.709+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/validate.py", line 29, in validate_csv
    df.to_csv(f'/opt/airflow/data/MTR_{date_str}.csv', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 3772, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/format.py", line 1186, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/formats/csvs.py", line 240, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
PermissionError: [Errno 13] Permission denied: '/opt/airflow/data/MTR_2025-11-01.csv'
[2025-11-01T17:26:47.750+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=validate_csv, task_id=validate_csv, execution_date=20251101T172612, start_date=20251101T172620, end_date=20251101T172647
[2025-11-01T17:26:47.791+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 23 for task validate_csv ([Errno 13] Permission denied: '/opt/airflow/data/MTR_2025-11-01.csv'; 243)
[2025-11-01T17:26:47.893+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-11-01T17:26:47.966+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
